FROM openjdk:8-jdk

# Install Firefox and dependencies
RUN apt-get update && apt-get install -y firefox-esr unzip wget

# Install Selenium
RUN wget -O /tmp/selenium-server-standalone.jar https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar

ADD . /app

WORKDIR /app

#Add Contrast agent
COPY --from=contrast/agent-java:latest /contrast/contrast-agent.jar contrast.jar

RUN ./gradlew build -x test --stacktrace

ENTRYPOINT [ "./gradlew", "cleanTest", "test" ]